In [1]:
# Note: AHS survey must be in the same directory as this notebook

In [1]:
import pandas as pd

In [2]:
 # from http://www2.census.gov/programs-surveys/ahs/2019/AHS%202019%20National%20PUF%20v1.1%20CSV.zip
df = pd.read_csv('./household.csv')

In [3]:
# from https://www.census.gov/data-tools/demo/codebook/ahs/ahsdict.html
# query parameters:
#   survey year: 2019 national
#   topics/subtopics: geography, demographics, equipment and appliances, utilities, income, 
#   availability: PUF
relevant_col_df = pd.read_csv('./ahsdict_25FEB21_12_18_01_80.csv')

In [10]:
shared_cols = []
for var in relevant_col_df['Variable'].tolist():
    if var in df.columns:
        shared_cols.append(var)

shared_ahs = df[shared_cols]

In [11]:
for col in shared_ahs.columns:
    try:
        shared_ahs[col] = shared_ahs[col].str.split("'").str[1].tolist()
    except:
        continue
    shared_ahs[col].astype(str)

/Users/haltriedman/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [12]:
shared_ahs

,DIVISION,OMB13CBSA,HEATTYPE,HEATFUEL,SUPP1HEAT,SUPP2HEAT,FIREPLACE,SOLAR,ACPRIMARY,ACSECNDRY,...,HHERRND,HINCP,FINCP,FS,ELECAMT,GASAMT,OILAMT,OTHERAMT,TRASHAMT,WATERAMT
0,5,37980,01,02,09,14,1,2,01,12,...,2,257000,257000,-6,230,30,0,0,30,80
1,1,99998,02,02,14,14,2,2,06,12,...,2,201000,201000,2,190,100,0,0,3,20
2,7,99998,01,02,14,14,4,-9,01,01,...,-6,-6,-6,-6,-6,-6,-6,-6,-6,-6
3,7,99998,01,02,14,14,2,2,01,12,...,2,66900,66900,2,100,60,0,0,10,3
4,4,99998,01,01,14,14,4,2,01,12,...,2,35000,35000,-6,2,0,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63180,3,99998,01,01,01,14,4,2,01,01,...,2,74000,74000,-6,90,40,200,0,3,240
63181,5,33100,03,01,14,14,4,2,01,12,...,2,207000,207000,-6,140,0,0,0,2,3
63182,5,99998,03,01,14,14,4,2,01,12,...,2,158100,158100,2,260,0,0,0,70,2
63183,5,33100,01,01,14,14,4,2,01,12,...,2,130200,130200,2,80,30,0,0,2,40
63184,5,12060,01,01,14,14,2,2,01,01,...,2,120000,120000,2,260,0,0,0,4,30

In [50]:
mapped_ahs = shared_ahs
for col in shared_ahs.columns:
    row = relevant_col_df.loc[relevant_col_df['Variable'] == col]
    desc = row['Description'].values[0]
    codes = row['Response Codes'].values[0].split('||')
    map_ = {}
    for code in codes:
        [k, v] = code.split(':', 1)
        if 'or' in k:
            [k1, k2] = k.split(' or ')
            k1 = k1.strip()
            k2 = k2.strip()
            map_[k1] = v
            map_[k2] = v
            continue
        k = k.strip()
        map_[k] = v
    mapped_ahs[col] = shared_ahs[col].map(map_).fillna(shared_ahs[col])

/Users/haltriedman/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [51]:
mapped_ahs['HINCP'] = mapped_ahs['HINCP'].astype(int)
mapped_ahs['FINCP'] = mapped_ahs['FINCP'].astype(int)
mapped_ahs

/Users/haltriedman/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/haltriedman/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DIVISION,OMB13CBSA,HEATTYPE,HEATFUEL,SUPP1HEAT,SUPP2HEAT,FIREPLACE,SOLAR,ACPRIMARY,ACSECNDRY,...,HHERRND,HINCP,FINCP,FS,ELECAMT,GASAMT,OILAMT,OTHERAMT,TRASHAMT,WATERAMT
0,South Atlantic,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",Forced warm-air furnace,Piped gas,"Wood burning, pot belly, Franklin stove(s), o...",No secondary supplemental heating,"Has usable fireplace, considers it heating eq...",No,Electric powered central air conditioning system,No secondary air conditioning,...,No,257000,257000,Not applicable,230,30,0,0,30,80
1,New England,All other metropolitan areas,Steam or hot water system,Piped gas,No primary supplemental heating,No secondary supplemental heating,"Has usable fireplace, not considered heating ...",No,2 room air conditioners,No secondary air conditioning,...,No,201000,201000,No,190,100,0,0,3,20
2,West South Central,All other metropolitan areas,Forced warm-air furnace,Piped gas,No primary supplemental heating,No secondary supplemental heating,No usable fireplace,Not reported,Electric powered central air conditioning system,Secondary electric powered central air condit...,...,Not applicable,-6,-6,Not applicable,-6,-6,-6,-6,-6,-6
3,West South Central,All other metropolitan areas,Forced warm-air furnace,Piped gas,No primary supplemental heating,No secondary supplemental heating,"Has usable fireplace, not considered heating ...",No,Electric powered central air conditioning system,No secondary air conditioning,...,No,66900,66900,No,100,60,0,0,10,3
4,West North Central,All other metropolitan areas,Forced warm-air furnace,Electricity,No primary supplemental heating,No secondary supplemental heating,No usable fireplace,No,Electric powered central air conditioning system,No secondary air conditioning,...,No,35000,35000,Not applicable,2,0,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63180,East North Central,All other metropolitan areas,Forced warm-air furnace,Electricity,Electric or gas cookstove,No secondary supplemental heating,No usable fireplace,No,Electric powered central air conditioning system,Secondary electric powered central air condit...,...,No,74000,74000,Not applicable,90,40,200,0,3,240
63181,South Atlantic,"Miami-Fort Lauderdale-West Palm Beach, FL",Electric heat pump,Electricity,No primary supplemental heating,No secondary supplemental heating,No usable fireplace,No,Electric powered central air conditioning system,No secondary air conditioning,...,No,207000,207000,Not applicable,140,0,0,0,2,3
63182,South Atlantic,All other metropolitan areas,Electric heat pump,Electricity,No primary supplemental heating,No secondary supplemental heating,No usable fireplace,No,Electric powered central air conditioning system,No secondary air conditioning,...,No,158100,158100,No,260,0,0,0,70,2
63183,South Atlantic,"Miami-Fort Lauderdale-West Palm Beach, FL",Forced warm-air furnace,Electricity,No primary supplemental heating,No secondary supplemental heating,No usable fireplace,No,Electric powered central air conditioning system,No secondary air conditioning,...,No,130200,130200,No,80,30,0,0,2,40
63184,South Atlantic,"Atlanta-Sandy Springs-Roswell, GA",Forced warm-air furnace,Electricity,No primary supplemental heating,No secondary supplemental heating,"Has usable fireplace, not considered heating ...",No,Electric powered central air conditioning system,Secondary electric powered central air condit...,...,No,120000,120000,No,260,0,0,0,4,30

In [53]:
# Now that data is clean, start analysis.
income_bins = [0, 20000, 40000, 60000, 80000, 100000, 120000, 140000, float('inf')]
regions = ["National",
           " New England",
           " Middle Atlantic",
           " East North Central",
           " West North Central",
           " South Atlantic",
           " East South Central",
           " West South Central",
           " Mountain",
           " Pacific"]
modes_of_analysis = ['HEATTYPE',
                     'HEATFUEL',
                     'HOTWATER',
                     'COOKFUEL',
                     'DRYER']

In [54]:
# get percentage breakdowns for a type of fuel source
def percent_df(df):
    percent_dict = {}
    for i in range(1, 150000, 20000):
        percent_list = []
        for row in df[i]:
            percent_list.append(row / df[i].sum())
        if i < 140000:
            percent_dict[f'income ${i-1}-{i+19999}'] = percent_list
        else:
            percent_dict[f'income ${i-1}+'] = percent_list
    return pd.DataFrame(percent_dict, index=df.index)

In [55]:
# Step 1.1: How many households are there in each income bracket?
mapped_ahs.HINCP.groupby(pd.cut(mapped_ahs.HINCP, income_bins)).size()

HINCP
(0.0, 20000.0]          9239
(20000.0, 40000.0]      9336
(40000.0, 60000.0]      7788
(60000.0, 80000.0]      6416
(80000.0, 100000.0]     4964
(100000.0, 120000.0]    3622
(120000.0, 140000.0]    2752
(140000.0, inf]         9228
Name: HINCP, dtype: int64

In [56]:
# Step 1.2: How many households are there total?
mapped_ahs.HINCP.groupby(pd.cut(mapped_ahs.HINCP, income_bins)).size().sum()

53345

In [57]:
def conduct_analysis():
    analysis_dict = {}
    
    for region in regions:
        analysis_dict[region] = {}
        for mode in modes_of_analysis:
            analysis_df = pd.DataFrame()
            if region != "National":
                analysis_df = mapped_ahs.loc[mapped_ahs.DIVISION == region][['HINCP', mode]]
            else:
                analysis_df = mapped_ahs[['HINCP', mode]]
            analysis_groups = analysis_df.groupby([mode, pd.cut(analysis_df.HINCP, income_bins)]).size().unstack()
            analysis_groups_percent = percent_df(analysis_groups)
            total_by_income = analysis_groups.sum(axis=1)
            
            analysis_dict[region][mode] = [analysis_groups, analysis_groups_percent, total_by_income]
    return analysis_dict

analysis_dict = conduct_analysis()

In [ ]:
# I've abstracted all of the logic from my analysis into a function and applied it programmatically. 
# Here's how to use this dict:
#   analysis_dict[<region>][<mode>][<0, 1, 2>]
#   regions: see the region list above. leading space is necessary as I haven't been able to get it to stop showing up.
#   mode: see mode list above.
#   <0, 1, 2>:
#        0 — raw counts of each category within each income bracket
#        1 — percentages of each category within each income bracket
#        2 — raw count of each category without income analysis

In [65]:
analysis_dict['National']['DRYER'][1]

,income $0-20000,income $20000-40000,income $40000-60000,income $60000-80000,income $80000-100000,income $100000-120000,income $120000-140000,income $140000+
DRYER,,,,,,,,
Unit does not have a working clothes dryer,0.390086,0.239610,0.165126,0.120012,0.084005,0.072612,0.066497,0.050390
Working LP (liquefied petroleum) gas clothes dryer,0.005412,0.006962,0.007704,0.008728,0.009065,0.007454,0.012355,0.010728
Working electric power clothes dryer,0.490746,0.608505,0.662815,0.679863,0.689565,0.684705,0.672965,0.653229
Working other fuel source powered clothes dryer,0.000433,0.000321,0.000257,0.000156,0.000201,0.000276,0.000000,0.000433
Working piped gas powered clothes dryer,0.113324,0.144602,0.164099,0.191241,0.217164,0.234953,0.248183,0.285219